# Generated by Django 4.2.5 on 2023-11-15 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormulaireSante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_remplissage", models.DateField()),
                ("periodicite_jours", models.IntegerField()),
                ("is_late", models.BooleanField(default=False)),
                ("poids", models.FloatField()),
                ("tour_de_taille_cm", models.FloatField()),
                ("frequence_cardiaque_min", models.IntegerField()),
                ("tension_arterielle_systolique_matin", models.FloatField()),
                ("tension_arterielle_systolique_soir", models.FloatField()),
                ("tension_arterielle_diastolique_matin", models.FloatField()),
                ("tension_arterielle_diastolique_soir", models.FloatField()),
                ("symptomes_cardiovasculaires", models.TextField()),
                ("nb_medicaments_jour", models.IntegerField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
