# Generated by Django 4.2.5 on 2023-11-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulairesante",
            name="periodicite_jours",
        ),
    ]
