# Generated by Django 4.2.5 on 2023-09-20 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "patient"),
                    ("medecin", "medecin"),
                    ("responsable", "responsable"),
                ],
                max_length=30,
                null=True,
                verbose_name="Rôle",
            ),
        ),
        migrations.CreateModel(
            name="medecinPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idMedecin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medecinPatient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "idPatient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patientMedecin",
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
